import { useEffect, useState } from "react";
import API from "../services/api";
import DepartmentCards from "../components/DepartmentCards";
import ActiveAssignments from "../components/ActiveAssignments";
import ResourceAllocation from "../components/ResourceAllocation";
import IncidentMapPreview from "../components/IncidentMapPreview";
import TicketTrendChart from "../components/TicketTrendChart";
import "../styles/Departments.css";

function Departments() {
    const [tickets, setTickets] = useState([]);
    const [stats, setStats] = useState(null);
    const [loading, setLoading] = useState(true);

    // Filter state
    const [filterOpen, setFilterOpen] = useState(false);
    const [filterPriority, setFilterPriority] = useState("");
    const [filterStatus, setFilterStatus] = useState("");
    const [filterDept, setFilterDept] = useState("");

    // Assignment modal
    const [assignOpen, setAssignOpen] = useState(false);

    useEffect(() => {
        const statsP = API.get("/stats")
            .then((res) => setStats(res.data))
            .catch(() => setStats(null));

        const ticketsP = API.get("/tickets", { params: { page: 1, limit: 100, order: "desc" } })
            .then((res) => setTickets(res.data.data || []))
            .catch(() => setTickets([]));

        Promise.all([statsP, ticketsP]).finally(() => setLoading(false));
    }, []);

    if (loading) {
        return (
            <div className="departments-page">
                <div className="loading-spinner"><div className="spinner" /> Loading departments...</div>
            </div>
        );
    }

    // Apply filters
    const filteredTickets = tickets.filter((t) => {
        if (filterPriority && t.priority !== filterPriority) return false;
        if (filterStatus && t.status !== filterStatus) return false;
        if (filterDept && t.assigned_department !== filterDept) return false;
        return true;
    });

    // Get unique departments for filter
    const allDepts = [...new Set(tickets.map((t) => t.assigned_department).filter(Boolean))];
    const allPriorities = [...new Set(tickets.map((t) => t.priority).filter(Boolean))];
    const allStatuses = [...new Set(tickets.map((t) => t.status).filter(Boolean))];

    const clearFilters = () => {
        setFilterPriority("");
        setFilterStatus("");
        setFilterDept("");
    };

    const hasFilters = filterPriority || filterStatus || filterDept;

    // Generate report handler
    const handleGenerateReport = () => {
        const total = filteredTickets.length;
        const open = filteredTickets.filter((t) => t.status === "Open").length;
        const closed = filteredTickets.filter((t) => t.status === "Closed").length;
        const inProgress = filteredTickets.filter((t) => t.status === "In Progress").length;
        const avgRps = total > 0
            ? (filteredTickets.reduce((s, t) => s + (t.rps_score || 0), 0) / total).toFixed(1)
            : 0;
        const critical = filteredTickets.filter((t) => t.priority === "Critical" || t.priority === "High").length;

        const deptCounts = {};
        filteredTickets.forEach((t) => {
            const d = t.assigned_department || "Unassigned";
            deptCounts[d] = (deptCounts[d] || 0) + 1;
        });
        const deptLines = Object.entries(deptCounts)
            .sort((a, b) => b[1] - a[1])
            .map(([name, count]) => `  • ${name}: ${count} tickets`)
            .join("\n");

        const report = `
═══════════════════════════════════════
        ROADNET.AI WEEKLY REPORT
═══════════════════════════════════════

Date: ${new Date().toLocaleDateString()}

SUMMARY
───────
Total Tickets:     ${total}
  Open:           ${open}
  In Progress:    ${inProgress}
  Closed:         ${closed}
Critical/High:    ${critical}
Avg. RPS Score:   ${avgRps}

DEPARTMENT BREAKDOWN
────────────────────
${deptLines}

═══════════════════════════════════════
Generated by RoadNet.AI Analytics Engine
        `.trim();

        // Create downloadable text file
        const blob = new Blob([report], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `roadnet_weekly_report_${new Date().toISOString().slice(0, 10)}.txt`;
        a.click();
        URL.revokeObjectURL(url);
    };

    // Export CSV handler
    const handleExportCSV = () => {
        const headers = "Ticket ID,Type,Priority,RPS Score,Zone,Department,Status,Timestamp\n";
        const rows = filteredTickets.map((t) =>
            `${t.ticket_id || ""},${t.type || ""},${t.priority || ""},${t.rps_score || ""},${t.zone || ""},${t.assigned_department || ""},${t.status || ""},${t.video_timestamp_formatted || ""}`
        ).join("\n");
        const blob = new Blob([headers + rows], { type: "text/csv" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `roadnet_tickets_${new Date().toISOString().slice(0, 10)}.csv`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="departments-page">
            {/* Header */}
            <div className="dept-header">
                <div className="dept-header-text">
                    <h1>Departmental Management</h1>
                    <p>Operational performance and resource allocation across civil sectors.</p>
                </div>
                <div className="dept-header-actions">
                    <button className="btn-filter" onClick={() => setFilterOpen(!filterOpen)}>
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" /></svg>
                        Filter{hasFilters ? " ●" : ""}
                    </button>
                    <button className="btn-assign-dept" onClick={() => setAssignOpen(true)}>+ Assign Department</button>
                </div>
            </div>

            {/* Filter Panel */}
            {filterOpen && (
                <div className="dept-filter-panel">
                    <div className="dept-filter-row">
                        <div className="dept-filter-field">
                            <label>Priority</label>
                            <select value={filterPriority} onChange={(e) => setFilterPriority(e.target.value)}>
                                <option value="">All</option>
                                {allPriorities.map((p) => <option key={p} value={p}>{p}</option>)}
                            </select>
                        </div>
                        <div className="dept-filter-field">
                            <label>Status</label>
                            <select value={filterStatus} onChange={(e) => setFilterStatus(e.target.value)}>
                                <option value="">All</option>
                                {allStatuses.map((s) => <option key={s} value={s}>{s}</option>)}
                            </select>
                        </div>
                        <div className="dept-filter-field">
                            <label>Department</label>
                            <select value={filterDept} onChange={(e) => setFilterDept(e.target.value)}>
                                <option value="">All</option>
                                {allDepts.map((d) => <option key={d} value={d}>{d}</option>)}
                            </select>
                        </div>
                        <button className="btn-clear-filters" onClick={clearFilters}>Clear</button>
                    </div>
                </div>
            )}

            {/* Department Cards */}
            <DepartmentCards tickets={filteredTickets} stats={stats} />

            {/* Middle: Assignments Table + Resource Sidebar */}
            <div className="dept-middle">
                <ActiveAssignments tickets={filteredTickets} />

                <div className="d-panel resource-sidebar">
                    <div className="d-panel-header">
                        <h3>Resource Allocation</h3>
                    </div>
                    <ResourceAllocation tickets={filteredTickets} stats={stats} />
                    <IncidentMapPreview />
                    <div className="report-buttons">
                        <button className="btn-report-primary" onClick={handleGenerateReport}>Generate Weekly Report</button>
                        <button className="btn-report-secondary" onClick={handleExportCSV}>Export Data (CSV)</button>
                    </div>
                </div>
            </div>

            {/* Bottom Trend Chart */}
            <TicketTrendChart tickets={filteredTickets} />

            {/* ===== Assign Department Modal ===== */}
            {assignOpen && (
                <div className="modal-overlay" onClick={() => setAssignOpen(false)}>
                    <div className="modal-content" onClick={(e) => e.stopPropagation()}>
                        <div className="modal-header">
                            <h2>Assign Department</h2>
                            <button className="modal-close" onClick={() => setAssignOpen(false)}>✕</button>
                        </div>
                        <div className="modal-body">
                            <div className="modal-field">
                                <label>Select Ticket</label>
                                <select className="modal-select" defaultValue="">
                                    <option value="" disabled>Choose a ticket...</option>
                                    {tickets.slice(0, 20).map((t) => (
                                        <option key={t.ticket_id} value={t.ticket_id}>
                                            #{t.ticket_id} — {(t.type || "").replace(/_/g, " ")} ({t.priority})
                                        </option>
                                    ))}
                                </select>
                            </div>
                            <div className="modal-field">
                                <label>Assign to Department</label>
                                <select className="modal-select" defaultValue="">
                                    <option value="" disabled>Select department...</option>
                                    {allDepts.map((d) => <option key={d} value={d}>{d}</option>)}
                                </select>
                            </div>
                            <div className="modal-field">
                                <label>Priority Override</label>
                                <select className="modal-select" defaultValue="">
                                    <option value="" disabled>Keep current</option>
                                    <option value="Critical">Critical</option>
                                    <option value="High">High</option>
                                    <option value="Moderate">Moderate</option>
                                    <option value="Low">Low</option>
                                </select>
                            </div>
                            <div className="modal-field">
                                <label>Notes</label>
                                <textarea className="modal-textarea" rows={2} placeholder="Assignment notes..." />
                            </div>
                            <button className="modal-submit" onClick={() => {
                                alert("Department assignment updated!");
                                setAssignOpen(false);
                            }}>Confirm Assignment</button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}

export default Departments;
